Accept and log warning when node fails to shutdown
[#148400217]

Signed-off-by: Andrew Thorburn <athorburn@pivotal.io>

diff --git a/rabbitmqctl/test-assets/rabbitmqctl-echo-with-fails b/rabbitmqctl/test-assets/rabbitmqctl-echo-with-fails
--- a/rabbitmqctl/test-assets/rabbitmqctl-echo-with-fails
+++ b/rabbitmqctl/test-assets/rabbitmqctl-echo-with-fails
@@ -1,3 +1,11 @@
 #!/bin/bash -e
 
-exit 1
+echo "Fail args"
+echo "${@}"
+
+if [[ "$3" == "rabbitmq@node1" ]]
+then
+  exit 1
+else
+  exit 0
+fi
