Refactor scripts
[#148578615]

Signed-off-by: Diego Lemos <dlresende@pivotal.io>

diff --git a/scripts/run-integration-tests b/scripts/run-integration-tests
--- a/scripts/run-integration-tests
+++ b/scripts/run-integration-tests
@@ -1,17 +1,31 @@
 #!/usr/bin/env bash
 
 set -e
-
-export BOSH_MANIFEST=${BOSH_MANIFEST:-$("$HOME/workspace/cf-rabbitmq-release/scripts/interpolate-manifest-for-bosh-lite")}
+set -o pipefail
 
 main() {
   eval "$(ssh-agent)"
   trap 'kill $SSH_AGENT_PID' EXIT
 
+  set_bosh_manifest
   add_bosh_ssh_key
   write_keys_to_file
   install_dependencies
-  run_integration_tests_individually_to_isolate_state
+  get_test_types | run_isolated_tests
+}
+
+set_bosh_manifest() {
+  if [ -n "$BOSH_MANIFEST" ]
+  then
+    export BOSH_MANIFEST
+    return
+  fi
+
+  local generator manifest_file
+  generator="$(dirname "$0")/interpolate-manifest-for-bosh-lite"
+  manifest_file="$( "$generator" )"
+
+  export BOSH_MANIFEST="$manifest_file"
 }
 
 add_bosh_ssh_key() {
@@ -39,12 +53,21 @@ install_dependencies() {
   bundle install
 }
 
-run_integration_tests_individually_to_isolate_state() {
-  spec_files=($(find spec/integration/ -type f))
+get_test_types() {
+  local base_name
+  base_name="$( basename "$0" )"
 
-  for spec_file in "${spec_files[@]}"
+  [[ $base_name =~ 'integration' ]] && echo 'integration'
+  [[ $base_name =~ 'system' ]]      && echo 'system'
+}
+
+run_isolated_tests() {
+  local base_dir
+  base_dir="$( dirname "$0" )/.."
+
+  while read -r spec_file
   do
-    bundle exec rspec "$spec_file" --fail-fast
+    find "${base_dir}/spec/${spec_file}" -type f -exec echo bundle exec rspec '{}' --fail-fast \;
   done
 }
 
